parameters:
  GroupVariablesName: ''

jobs:

- job: print_variable
  displayName: 'Print Group Variables inside of template'
  variables:
  - group: ${{ parameters.GroupVariablesName }}
  steps:
  - script: |
     echo webAppName '$(webAppName)'
     echo defaultVar '$(defaultVar)'
