trigger:
- master

variables:
- name: defaultVar
  value:  'value define yml on project repo'
- group: variables-example-outside


resources:
  repositories:
    - repository: yml_reference
      type: github
      ref: refs/heads/yml_reference
      name: enamba/azure_devops
      endpoint: enamba

jobs:
- job: print
  steps:
  - script: echo '$(defaultVar)'
- template: arch_group_variables.example.yml@yml_reference
  parameters:
    group-variables: 'variables-example-inside'

