trigger:
  branches:
    include:
    - master
    - feature/*
    - sprint/*
    - bugfix/*
  tags:
    include:  
    - to-production
    - development
    - to-quality-assurance

variables:
  - group: gitflow-example

stages:
- stage: Log_before
  jobs:
  - job: logbefore
    steps:
    - script: |
        echo teamProjectID $(teamProjectID)
        echo pipelineID $(pipelineID)

- stage: Build
  jobs:
  - job: BuildAppPHP
    condition: contains(variables['Build.SourceBranch'],'refs/heads')
    displayName: BUILD
    steps:
    - template: build.yml
      parameters:
        rootFolder: $(System.DefaultWorkingDirectory)

- stage: Deploy
  jobs:
  - job: DEPLOY
    condition: contains(variables['Build.SourceBranch'],'refs/tags')
    displayName: DEPLOY
    steps:
    - template: deploy.yml
      parameters:
        rootFolder: $(System.DefaultWorkingDirectory)
        azureSubscription: $(azureSubscription)
        version: $(version)
        environment: $(environment)
        webAppName: $(webAppName)
        teamProjectID: $(teamProjectID)
        pipelineID: $(pipelineID)

- stage: Log_after
  jobs:
  - job: logafter
    steps:
    - script: echo log after
