trigger:
- master

variables:
- name: defaultVar
  value:  'value define yml on project repo'
- group: variables-example-outside


resources:
  repositories:
    - repository: yml_reference
      type: github
      ref: refs/heads/yml_reference
      name: enamba/azure_devops
      endpoint: enamba

jobs:
- job: print
  steps:
  - script: |
      echo defaultVar '$(defaultVar)'
      echo outsidevar '$(outsidevar)'

      branchOrTagName=$(echo $(Build.SourceBranch) | awk -F "/" '{print $3}')
      echo "##vso[task.setvariable variable=branchOrTagName]$branchOrTagName"
- template: arch_group_variables.example.yml@yml_reference
  parameters:
    GroupVariablesName: 'variables-example-$(branchOrTagName)'

