trigger:
- master

variables:
- name: defaultVar
  value:  'value define yml on project repo'
- group: variables-example-outside


resources:
  repositories:
    - repository: yml_reference
      type: github
      ref: refs/heads/yml_reference
      name: enamba/azure_devops
      endpoint: enamba

jobs:
- template: components/GetNameOfRef.example.yml@yml_reference
- template: arch_group_variables.example.yml@yml_reference
  parameters:
    GroupVariablesName: 'variables-example-${{ branchOrTagName }}'
