trigger:
- master

variables:
- name: app_target
  value:  'app-example'
- group: variables-example-outside


resources:
  repositories:
    - repository: yml_reference
      type: github
      ref: refs/heads/yml_reference
      name: enamba/azure_devops

jobs:
- job: print
  steps:
  - script: echo '$(webAppName)'
- template: arch_node-01.example.yml@ci_yml_reference
  parameters:
    app_target: $(app_target)
    group-variables: 'variables-example-inside'

