jobs:
- job: deploy_app
  displayName: 'Deploy application'

  steps:
    - script: |
        echo outsidevar 
        echo namba

    - task: git-tag-on-release-task@9
      inputs:
        staticTagName: 'new_namba-1'