jobs:
- job: buildAndPushDocker
  steps:
    - powershell: | 
        $branchOrTagName = '$(Build.SourceBranch)' |  %{$_.Split("/")[2];}
        Write-Host "##vso[task.setvariable variable=branchOrTagName]$branchOrTagName"
      condition: eq( variables['Agent.OS'], 'Windows_NT' )
    - bash: |
        branchOrTagName=$(echo $(Build.SourceBranch) | awk -F "/" '{print $3}')
        echo "##vso[task.setvariable variable=branchOrTagName]$branchOrTagName"
      condition: eq( variables['Agent.OS'], 'Linux' )